/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package facturacion;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Set;

/**
 *
 * @author estudiante
 */
public class JFactura extends javax.swing.JFrame {

    private cliente currentCliente;
    private Producto currentproduct;
    private DefaultTableModel modelo;
    private double acumulador = 0;
    private double acumuladoriva = 0;
    private double acumuladorbruto = 0;
    
    
    public JFactura() {
        initComponents();
        inicializarModelo();
    }
    
    private void inicializarModelo() {
        String[] columnNames = {"Num Producto", "Producto", "Precio", "Iva", "Precio con Iva"};
        modelo = new DefaultTableModel(columnNames, 0);
        tablaproductos.setModel(modelo);
    }
    

   
    public void crear_cliente() {
        String nombre = nombreField.getText();
        String cedula = cedulaField.getText();
        String direccion = DireccionField.getText();
        String telefono = TelefonoField.getText();
        String correo = correoField.getText();
        

        currentCliente = new cliente(nombre, cedula, direccion, telefono, correo);
    }
    
    public void encontrar_producto(){
        String codigo = codproductotf.getText();
        
        currentproduct = new Producto(codigo);
        
    }
public boolean obtener_datos(String codigo) {
    currentproduct = new Producto(codigo); // Asegúrate de inicializar currentproduct aquí

    String pronum = null; 
    String descripcion = null;
    int cantidad = 0;
    double precio = 0;
    double iva = 0.0;

    boolean bandera = false;

    String sql = "SELECT PROCODIGO, PRODESCRIPCION, PROSALDOFINAL, PROPRECIOUM, PROIVA FROM productos WHERE PROCODIGO = ?";

    try (Connection conn = conexionBD.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, codigo);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            pronum = rs.getString("PROCODIGO");
            descripcion = rs.getString("PRODESCRIPCION");
            cantidad = rs.getInt("PROSALDOFINAL");
            precio = rs.getDouble("PROPRECIOUM");
            iva = rs.getDouble("PROIVA");

            currentproduct.setDescripcion(descripcion);
            currentproduct.setIva(iva);
            currentproduct.setProPrecio(precio);
            currentproduct.setProsaldofinal(cantidad);
            bandera = true;
        } else {
            System.out.println("No se encontró el producto con el código: " + codigo);
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }

    return bandera;
}



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numerofacturafield = new javax.swing.JTextField();
        nombreField = new javax.swing.JLabel();
        cedulaField = new javax.swing.JLabel();
        TelefonoField = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DireccionField = new javax.swing.JLabel();
        nombretexf = new javax.swing.JTextField();
        cedulatextfiel = new javax.swing.JTextField();
        telefonotextf = new javax.swing.JTextField();
        direcciontextfield = new javax.swing.JTextField();
        buscarclientebuton = new javax.swing.JButton();
        correojlabel = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        consumidorfinalb = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproductos = new javax.swing.JTable();
        labelcodigoproducto = new javax.swing.JLabel();
        codproductotf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spinercantidad = new javax.swing.JSpinner();
        agregarproductoboton = new javax.swing.JButton();
        totaltextfield = new javax.swing.JLabel();
        totalfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalivatf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalnetotf = new javax.swing.JTextField();
        botonverobjeto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nombreproductotf = new javax.swing.JTextField();
        Guardadofact = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        generarnuevafac = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        precioprod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        formasdepago = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel1.setText("Numero de factura:  ");

        numerofacturafield.setEditable(false);
        numerofacturafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerofacturafieldActionPerformed(evt);
            }
        });

        nombreField.setText("Nombre:");

        cedulaField.setText("Cédula: ");

        TelefonoField.setText("Teléfono:");

        DireccionField.setText("Dirección");

        nombretexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretexfActionPerformed(evt);
            }
        });

        telefonotextf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonotextfActionPerformed(evt);
            }
        });

        buscarclientebuton.setText("Buscar cliente");
        buscarclientebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclientebutonActionPerformed(evt);
            }
        });

        correojlabel.setText("Correo");

        correoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoFieldActionPerformed(evt);
            }
        });

        consumidorfinalb.setText("Consumidor final");
        consumidorfinalb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumidorfinalbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(TelefonoField)
                                            .addComponent(cedulaField)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel6))
                                            .addComponent(correojlabel))
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DireccionField)
                                        .addGap(18, 18, 18))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(nombreField)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direcciontextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(correoField)
                            .addComponent(cedulatextfiel)
                            .addComponent(telefonotextf)
                            .addComponent(nombretexf))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(numerofacturafield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consumidorfinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarclientebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numerofacturafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombretexf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarclientebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedulaField)
                    .addComponent(cedulatextfiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoField)
                    .addComponent(telefonotextf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionField)
                    .addComponent(direcciontextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consumidorfinalb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correojlabel)
                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Producto", "Descripcion", "Precio Unitario", "Cantidad", "Iva", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaproductos);
        if (tablaproductos.getColumnModel().getColumnCount() > 0) {
            tablaproductos.getColumnModel().getColumn(0).setResizable(false);
            tablaproductos.getColumnModel().getColumn(1).setResizable(false);
            tablaproductos.getColumnModel().getColumn(2).setResizable(false);
            tablaproductos.getColumnModel().getColumn(3).setResizable(false);
            tablaproductos.getColumnModel().getColumn(4).setResizable(false);
            tablaproductos.getColumnModel().getColumn(5).setResizable(false);
        }

        labelcodigoproducto.setText("Código del producto :");

        codproductotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codproductotfActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad : ");

        agregarproductoboton.setText("Agregar Producto");
        agregarproductoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarproductobotonActionPerformed(evt);
            }
        });

        totaltextfield.setText("total unitario");

        totalfield.setEditable(false);
        totalfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalfieldActionPerformed(evt);
            }
        });

        jLabel4.setText("total: iva");

        totalivatf.setEditable(false);
        totalivatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalivatfActionPerformed(evt);
            }
        });

        jLabel5.setText("Total neto");

        totalnetotf.setEditable(false);

        botonverobjeto.setText("Buscar producto");
        botonverobjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonverobjetoActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre producto : ");

        nombreproductotf.setEditable(false);
        nombreproductotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreproductotfActionPerformed(evt);
            }
        });

        Guardadofact.setText("Guardar Factura");
        Guardadofact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardadofactActionPerformed(evt);
            }
        });

        jButton2.setText("Previsualizacion factura");

        generarnuevafac.setText("generar nueva factura");
        generarnuevafac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarnuevafacActionPerformed(evt);
            }
        });

        jLabel9.setText("Precio del Producto:");

        precioprod.setEditable(false);

        jLabel10.setText("Forma de pago:");

        formasdepago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia", " " }));
        formasdepago.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formasdepagoComponentAdded(evt);
            }
        });
        formasdepago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formasdepagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelcodigoproducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codproductotf)
                                    .addComponent(nombreproductotf)
                                    .addComponent(precioprod, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarproductoboton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonverobjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(10, 10, 10))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(formasdepago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(255, 255, 255)
                            .addComponent(totaltextfield)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Guardadofact, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generarnuevafac)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalfield, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(totalivatf)
                        .addComponent(totalnetotf)))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelcodigoproducto)
                            .addComponent(codproductotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nombreproductotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(precioprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spinercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(botonverobjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agregarproductoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaltextfield)
                    .addComponent(jLabel10)
                    .addComponent(formasdepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(totalivatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalnetotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addComponent(generarnuevafac))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Guardadofact)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numerofacturafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerofacturafieldActionPerformed
        
    }//GEN-LAST:event_numerofacturafieldActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void nombretexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretexfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretexfActionPerformed

    private void telefonotextfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonotextfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonotextfActionPerformed

    private void buscarclientebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclientebutonActionPerformed
        
        crear_cliente();

        if (currentCliente.comprobarcliente() == true) {
            JOptionPane.showMessageDialog(null, "Se encontró el cliente: \n" + currentCliente);
        } else {
            JOptionPane.showMessageDialog(null, "No se encuentra el cliente: \n");
            
        }
    

    }//GEN-LAST:event_buscarclientebutonActionPerformed

    private void correoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFieldActionPerformed

    private void codproductotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codproductotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codproductotfActionPerformed

    private void agregarproductobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarproductobotonActionPerformed
        tablaproductos.setModel(modelo);
        String product = codproductotf.getText();
        int cantidad = Integer.parseInt(String.valueOf(spinercantidad.getValue()));

        if (obtener_datos(product) && currentproduct != null && currentproduct.ComprobarProducto(cantidad)) {
            Object[] rowdata = {tablaproductos.getRowCount() + 1, currentproduct.getNumeroproducto(), currentproduct.getDescripcion(), currentproduct.getProPrecio(), currentproduct.getIva(), currentproduct.sumador(currentproduct.getProPrecio(), currentproduct.getIva())};
            modelo.addRow(rowdata);

            acumulador = acumulador + currentproduct.sumador(currentproduct.getProPrecio(), currentproduct.getIva());
            acumuladoriva = acumuladoriva + currentproduct.getIva();
            acumuladorbruto = acumuladorbruto + currentproduct.getProPrecio();

            totaltextfield.setText("" + acumulador);

        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el producto o el cliente: \n" + product);
        }
    }//GEN-LAST:event_agregarproductobotonActionPerformed

    private void totalfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalfieldActionPerformed

    }//GEN-LAST:event_totalfieldActionPerformed

    private void totalivatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalivatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalivatfActionPerformed

    private void botonverobjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonverobjetoActionPerformed
        String product = codproductotf.getText();  // Usar getText() para obtener el valor del campo de texto

        if (obtener_datos(product)) {
            nombreproductotf.setText(currentproduct.getDescripcion());
            precioprod.setText("" + currentproduct.getProPrecio());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró el producto: \n" + product);
        }

    }//GEN-LAST:event_botonverobjetoActionPerformed

    private void consumidorfinalbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumidorfinalbActionPerformed
        nombretexf.setText("Consumidor Final");
        cedulatextfiel.setText("9999999999");
        telefonotextf.setText("0000000000");
        direcciontextfield.setText("Dirección Genérica");
        correoField.setText("consumidor@final.com");

        nombretexf.setEditable(false);
        cedulatextfiel.setEditable(false);
        telefonotextf.setEditable(false);
        direcciontextfield.setEditable(false);
        correoField.setEditable(false);
    }//GEN-LAST:event_consumidorfinalbActionPerformed

    private void generarnuevafacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarnuevafacActionPerformed
        
    }//GEN-LAST:event_generarnuevafacActionPerformed

    private void nombreproductotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreproductotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreproductotfActionPerformed

    private void GuardadofactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardadofactActionPerformed
        
    }//GEN-LAST:event_GuardadofactActionPerformed

    private void formasdepagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formasdepagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formasdepagoActionPerformed

    private void formasdepagoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formasdepagoComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formasdepagoComponentAdded

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFactura().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DireccionField;
    private javax.swing.JButton Guardadofact;
    private javax.swing.JLabel TelefonoField;
    private javax.swing.JButton agregarproductoboton;
    private javax.swing.JButton botonverobjeto;
    private javax.swing.JButton buscarclientebuton;
    private javax.swing.JLabel cedulaField;
    private javax.swing.JTextField cedulatextfiel;
    private javax.swing.JTextField codproductotf;
    private javax.swing.JButton consumidorfinalb;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correojlabel;
    private javax.swing.JTextField direcciontextfield;
    private javax.swing.JComboBox<String> formasdepago;
    private javax.swing.JButton generarnuevafac;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcodigoproducto;
    private javax.swing.JLabel nombreField;
    private javax.swing.JTextField nombreproductotf;
    private javax.swing.JTextField nombretexf;
    private javax.swing.JTextField numerofacturafield;
    private javax.swing.JTextField precioprod;
    private javax.swing.JSpinner spinercantidad;
    private javax.swing.JTable tablaproductos;
    private javax.swing.JTextField telefonotextf;
    private javax.swing.JTextField totalfield;
    private javax.swing.JTextField totalivatf;
    private javax.swing.JTextField totalnetotf;
    private javax.swing.JLabel totaltextfield;
    // End of variables declaration//GEN-END:variables
}
